:toc: left
:toclevels: 3
:toc-title: Contents
:sectnums:

:imagesdir: ../images

= Annie Leibovitz

* robert frank
* where is the line between observing and creating?
* "capturing" the person - baloney!
* she loves "series"/"photostory"
* what makes a great photograph?
* take a photo from a newspaper that you love, cut it out and paste onto the wall / journal whatever - see how it affects what you do.
* light; where's it coming from, 
* light; ambient light, plus a small key light
** strobe about a stop under the ambient light

When she is taking a portrait, she will often research for months to understand what she wants the picture to be.


== Assignment
1. Photograph an elderly person. Ask them if they have any photographs of them when they were young, and see how those inform you when you're photographing them now?
1. Take a willing subject, take pictures at three times of the day; morning; midday, evening.
1. Photgraph someone in a simple background, and also with a background that means something to the person. What are the results? How does it affects the subject? She's not sure about this - just explore

1. Photograph someone close to you. Before you look at the images, reflect on what it meant to photograph these people and what was challenging.

1. Look back at some of your old work, and learn from it. What was good about those early days?

1. Photo essay - tell a story

1. Photographing someone - go back and do some more if you need to.

1. discuss your work with others - critique!

1. work with a friend who has some input, and take a picture of a mutual friend