:toc: left
:toclevels: 3
:toc-title: Contents
:sectnums:

:imagesdir: ../images

= Annie Leibovitz

* robert frank
* where is the line between observing and creating?
* "capturing" the person - baloney!
* she loves "series"/"photostory"
* what makes a great photograph?
* take a photo from a newspaperthat you love, cut it out and paste onto teh wall / journal whatever - see how it affects what you do.
* light; where's it coming from, 
* light; ambient light, plus a small key light
** strobe about a stop under teh ambient light

== Assignment
1. Photograph an elderly person. Ask them if they have any photographs of them when they were young, and see how those inform you when you're photographing them now?
1. Take a willing subject, take pictures aat three times of the day; morning; midday, evening.
1. Photgraph someone in a simple background, and also with a background that means something to the person. What are the results? How does it affects the subject? She's not sure about this - just explore



