:toc: left
:toclevels: 5
:toc-title: Contents

= Brian Lloyd Duckett
Ian Cummings <ian.cummings@bigfoot>
V0.1, Sep-2026
:Author: Ian Cummings
:Email: 
:Date: Sep 2026
:Revision: V0.1

:numbered:

== Locations

=== Shoreditch (#15)
==== Brick Lane
The main thoroughfare through Shoreditch is Brick Lane. Sunday market around the Old Truman Brewery. Opening Hours

* Sundays (Main Market Day): Generally open from 9:00 AM to 5:00 PM (street markets and general stalls peak on Sundays).

* Brick Lane Vintage Market: Open 7 days a week (Monday–Friday 11:00 AM–6:30 PM, Saturday 11:00 AM–6:00 PM, Sunday 10:00 AM–6:00 PM).

* Saturday Markets (Upmarket / Backyard Market): Typically open 11:00 AM to 6:00 PM.

==== Colombia Road Flower Market
On Sundays 8am until 3 ish. It's a 6 min walk going north towards Hackney. Probably need a wide lens; 28mm, 24mm, even wider!

https://columbiaroad.info/find-us/

The Flower Market is situated in the London borough of Tower Hamlets. It’s a leisurely walk or cycle ride from any of the surrounding boroughs of Islington, Hackney, and the City of London.

Walking & Public transport +
A stroll along Regent’s Canal is a favourite way of reaching the market. If you’re coming from further afield, the nearest station is Hoxton (Overground), which is roughly a 7 minute walk away, but Liverpool Street, Old Street, Shoreditch or Bethnal Green tube stations will offer you a 20 minute walk through the surrounding area and sites of interest.
Buses are the 26, 55 or the number 8.

==== Other stuff
Prepare a project.

==== Books
* Shoreditch Wildlife by Dougie Wallace
* East Ended, also by Dougie Wallace

==== Pubs
* Pride of Spitlfields, Henidge Street (close to brick Lane)
* Royal Oak (nr flower market0 - a bit up-market
* westerly; Bricklayers Arms corner Rivington Street & Charlotte Road (close to Old St.)

== Books

=== Fred Herzog (#15)
Apart from his seminal work (__Modern Color______), he has some monochrome work; _Black & White_ 

