:toc: left
:toclevels: 3
:toc-title: Contents

= Food

* Colour +
Important - set white balance correctly

* Light +
** Best light is soft and even, so softboxes etc. If that isn't practical, in front of a window is usually good. Veil the window if light is too hard. Alternatively - go outside! +
** Choose light appropriate to dish; summer/wintery dishes.
** reflectors +

* background +
Simple, nothing to detract from the main subject (the food). +

** Wooden table says rustic
** outside table says picnic/al fresco
** square plates say minimalism +
White is good but can be unimaginative, so try complimentary colours; darker colours for warmth, lighter colours for freshness

* Composition +
** add cutlery? +
** Focus +
Towards the front of the dish. Maybe keep 5.6 or above or else depth of field will be too narrow. +
** Cropping +
Not too close, give the food some context and include other relevant objects to give context.
** angle +
Stacked food (pancakes) looks good from the side, flat food (pizza) looks better from above. +
Tablescapes showing several components are good too. +

Consider what makes the food look appealing and find a way to sell that feature. A wide aperture works well on products that are presented in rows or clusters and are easily identifiable such as; cupcakes, biscuits, and sweets etc.  If the product is small and plentiful, such as coffee beans or nuts for instance, consider cropping in close to fill the entire frame. Also consider your angle to add interest and sense of depth, scale and perspective. Make the most of interesting patterns and shapes by highlighting this as the focus. Including props to present the product can work well to convey a sense of scale or action, such as ladles, bowls, scales, pestle and mortar, or for drinks consider decorating the glass or backdrop with the fruit or flavours used in the ingredients.

* Action +
There is a lot to be said for in-progress recipe shots that show food actually being prepared. Consider shots that feature motion such as chopping, blending, frying, rising in the oven etc and using a longer exposure to convey the sense of motion and speed. But don’t forget the tripod!









(https://digital-photography-school.com/food-photography-5-simple-ways-to-get-stronger-shot/)
