:toc: left
:toclevels: 3
:toc-title: Contents

= Projects & Photographic Essays

== Photo Essays

1. Do your research - what other maerial is out there?

1. Tell a story - it needs to be more than a set of images on a similar theme. It should have a beginning, middle, and end.

1. Have a cohesive style - for example; don't mix mono & colour, natural & artificial light etc

1. Create a strong edit - Be brutal; keep only the strongest or best to create the story arc. A suitable number of images is 20?

1. Ask people you trust for input

1. Add some text - context, maybe some captions.

1. General atmospheric shots

1. Some semblance of time passing

1. Document events/happenings during event.

== Projects
A collection of images on a theme

* could tell a story
* common aesthetic (a set of principles underlying the work)
* Common Theme; location, activity
* Focussed body of work
* common visual glue connecting images (cohesion)

1. Get an idea
1. Add the name to a notebook
1. Let it develop over time, add detail and fill in gaps until you have a well formed idea of what the project is about. This can take weeks or months.

Examples of projects that have been made into books are

* Americans by Robert Frank
* On the Night bus by Nick Turpin

== Outlets for Projects & Phot Essays
This can be print; a zine, postcards, or prints. Ask local coffee shops to display - take frames samples.

Publishers: http://blurb.com & http://mixam.com