
== January: What Is It?
Photograph common everyday objects from a different angle or perspective so that they are not immediately recognisable.
This is a challenge in observation, looking at things in a new way. If the image is close up it is also an exercise in Depth of Field. +
*Submit by: 22 January*

== February: Smoke
Capturing an image of smoke can be a real challenge. Have a go at a few different types.... perhaps smoke from a chimney, a log fire, or a smouldering joss stick on a table top. You choose.
This is a challenge in lighting, exposure and background. +
*Submit by: 19 February*

== March: Winter
Wide interpretation. From frost on a tree branch to snow covered rooftops. From icy puddles to windswept pedestrians. You can take photos through a window and stay warm, or put on your winter warmers and venture outside.
This is a challenge about composition, lighting, exposure and contrast. +  
*Submit by: 26 March*

== April: Raindrops
Wide interpretation. From droplets running down a window pane to drips from a gutter. From catching light on leaves in a garden to making patterns in a puddle.
This is a challenge about composition, lighting, and possibly close up too.
*Submit by: 23 April​*

== May: Spring
Wide interpretation. From birds on a branch to snowdrops emerging in a field.
This is a challenge about composition and lighting +
*Submit by: ​​21 May*

== June: Street
Wide interpretation. From architecture to urban decay. From people to graffiti.
This is a challenge about observation, perspective, candid portraiture. +
*Submit by: ​​25 June*

== July: Contrast
Capturing light and dark in one image. Any subject.
This is a challenge about exposure. +
*Submit by: ​​23 July*

== August: Four Elements
In ancient Greece it was proposed that everything in the world could ultimately be composed of four elements in different combinations of Earth, Water, Air and Fire. In the late 1700s science proved that this was not the case and our modern understanding of matter and the periodic table was born. However, the idea of the four elements endures to this day and is used often in art and creativity. Try to capture one or more of the four elements in your photos and portray them in any way you wish.
This is a challenge about interpretation, perspective and composition. It can also embrace the technical aspects of exposure, focus and DoF. +
*Submit by: ​​20 August*

== September: Architecture
Photography of building exteriors and interiors, as well as bridges, other structures, and cityscapes.
This is a challenge about perspective, composition, lighting and lens distortion. +
*Submit by: ​​24 September*

== October: Harvest
Wide interpretation. From a close-up of an ear of wheat to a table top still life composition. From a farmer looking at a crop to a combine harvester driving across a field.
This is a challenge about perspective, composition, lighting, landscape and portraiture. +
*Submit by: ​​22 October*

== November: Disappearing Technology
Only a few years ago a mobile telephone was a brick that made voice calls and sent text messages. Today it is a fully featured ultra compact computer that also makes voice calls. A few years ago most households had at least one television. A large behemoth that needed its own corner in the living room and a large aerial on the roof. Today TVs are being replaced with portable tablets and programs are streamed online. Capture images that represent the technology that is fast disappearing from our lives.
This is a challenge about perspective, composition, lighting, close-up, DoF. +
*Submit by: ​​19 November*

== December: Celebrations
After the muted celebrations at the end of 2020, we all hope that 2021 will bring some return to normality. The celebrations around Christmas and New Year at the end of 2021 promise to be an outpouring of happiness and hope for much of the country. Try to capture some of this with your camera.
This is a challenge about composition, low  light, candid portraiture. +
*Submit by: ​​7 Jan 2022*