:toc: left
:toclevels: 5
:toc-title: Contents
:sectnums:
:sectnumlevels: 7

// :stylesheet: gv.css
:imagesdir: ../images

= Cars

== Golf
1. cambelt


== Skoda Fabia4

* link:https://go.skoda.eu/owners-manuals[Owners manual] +
Ours should be link:https://digital-manual.skoda-auto.com/w/en_GB/show/96df8a849b8a94039026acbe570f1d43_12_en_GB?ct=db9d0dfaf39abe43ac1445257d17f499_1_en_GB#titled22337491e9572[this] one

* link:https://go.skoda.eu/video-manuals-fabia4[Video Tutorials]

* Wipers +
link:https://www.boschwiperblades.com/xc/en-gb/basic-page.html/-/en-gb/478dafb54dab9771f6adabf9705fe54dd0d454ee/period_5046_2949_06_2021_12_9999/SKODA_Fabia_2021[Bosch website]

** front: 26" & 18" (650mm/450mm); link:https://www.wiperblades.co.uk/products/bosch-aerotwin-twin-pack-a864s-twin-pack-wiper-blades[Bosch A 864 S]
** rear: 12" (300mm) ; Bosch A 303 H 

** Tyres
195/55 R16 91V

Front: Michelin Cross Climate2, Tyrebarn £130 each @ 18513, 19th Nov 2025

== Dates
* Registered: 9 March 2023
* MOT due: 8 March 2026

=== When is the next Service?
1. Go into the car and turn on the infotainment,
1. Get to the menu screen and click on Vehicle,
1. Click on the bottom right of the screen where it says settings,
1. Scroll down to the section titled ‘Service’
1. This will display when the next one is due.


== Snow Foam

* Don't do it on hot days - will bubble and dry off too quickly
* if lots of mud etc, then hose off, but then allow car to dry
* start with dry car
* spray foam along the length of car starting from bottom up - 3 feet away for a lance
* leave on 5-10 mins - don't let it start drying (fill up normal contact wash buckets etc)
* rinse off - top to bottom
* wash car (2 bucket method)

* 2 bucket method
** 1 bucket wash, 1 bucket rinse
use microfibre mitt, load from wash - wash car, rinse off in rinse bucket

* lance should have metal gauze rather than plastic

* autoglym, lance 400ml water, 100ml product -> lance container

lance adaptor needs to fit your pressure washer +

https://www.karchercenterjhs.co.uk/karcher-fj6-pressure-washer-snow-foam-lance-2.643-147.0#:~:text=Using%20the%20Karcher%20FJ%206,Gun%20and%20apply%20the%20foam.

== Sam's Snow Foam Pump Sprayer 

* link:https://www.samsdetailing.co.uk/collections/snow-foam-lances/products/pump-sprayer#dilutions[Dilutions]

	
 

|====
| | | Water | Nozzle
| Snow Foam | 50ml | 1 litre | Black *
|Ceramic Foam | 50ml | 400ml | black
| Wheel & Tyre Cleaner | Ready For Use | N/A | Black or white
| Wheel Soap | Ready For Use | N/A | Black
| Ceramic Boost | Ready For Use | N/A | White
| Iron Reactor | Ready For Use | N/A | White
| Exterior Detailer | Ready For Use | N/A | White
|====

+++*+++ 20 off car washes for £10 - much better than EzCarCare

== EzCarCare

link:EZ+2025+Detailing+Guide_Compressed.pdf[Detailing Guide]

NOTE: Not in direct sunlight

https://www.youtube.com/watch?v=DVp8m6-VHU0

1. **Citrus Wash**: pre-wash, an alternative/addition to snow foam, apply by trigger +
10:1 for maintenance, up to 4:1 for stubborn organics (but may will degrade your wax) +
spray on, few minutes, hose off

1. **SubZero**/**Artic Meltdown**: Snow foam, apply via lance/pump sprayer +
4:1, 100ml:400ml water = 1 car, wash off after a few minutes +
(1l water to 250ml foam = 1/2 bottle @ £8/bottle = £4/car!)

1. **Viper**, non-acid wheel cleaner, 10:1 maintenance, 3or4:1 standard, 1:1 heavy soiling +
spray on, few minutes, hose off +
Can also use with detailing brushes while doing contact wash.

1. Ember(mango)/Cherry Bomb, **shampoo**, 250:1 dilutable +
40ml:10l, 4 capfuls:1/2 10l bucket +
Shushz it up with hose, use wash mitt/pad, 2 bucket method. Use with detailing brushes if necessary. +
Hose off

1. **Reigning Iron**: Bleeding Fallout Remover (very smelly) +
Non-dilutable, apply and leave to dry 5-10mins +
Product will turn purple when reacting: +
"Iron Fallout Remover should be applied at Step 4: Decontamination, immediately following the wash stage. By this point, most of the dirt will have been removed, leaving only contaminants behind." +
"... fallout remover is formulated with a blend of advanced cleaning agents that latch onto iron particles, causing them to dissolve and be safely removed from the surface of your vehicle." +
__Purpose:
To safely and effectively remove embedded iron particles and other contaminants from the vehicle's paint, wheels, chrome, and glass. 
How it works:
The product uses chemicals to dissolve and break down the iron particles, allowing them to be rinsed away. 
Benefits:
Prevents corrosion and damage to the paint, improves the appearance of the vehicle, and prepares the surface for waxing or ceramic coatings. 
Types:
Some products are pH neutral, making them safe for use on various surfaces. Others may have a more acidic formula that requires more caution. 
Application:
Typically applied after washing and before waxing or coating. 
Color Change:
Many products change color when they react with iron, providing visual confirmation of the process.__

1. **Eliminator**: Paint cleansing panel wipe. Use before applying wax, removes lasresidual chemicals/oils. Spray onto microfibre cloth, apply, then buff dry.

1. **Ceramic Wax**: two swipes of applicator -> wing/1/2 door. Straight lines or circles +
Leave on 10-15mins to cure. Swipe finger, if smears then leave longer. +
Buff off with microfibre cloth. +
One panel at a time or whole car on then off?

1. *Sleek* - interior dressing for interior plastic. +
Two to three squirts onto cloth, wipe to apply. Buff off. +

1. *Clarity 2.0* - window/glass cleaner. Squirt on cloth, buff off.

1. *GTR* - tar removal prior to reigning Iron.

1. *Gloss Boss* - top ups for maintenance washes

1. *Slick* - for rubber

1. *Liquid - Ceramic Shampoo* +
1:250 dilution (40ml:10l, 4 capfuls:1/2 10l bucket), jushz it up with hose +
ceramic shampoos don'y suds up as other shampoos +
can also use in a lance/pump sprayer


1. *Fusion* - Ultra hydrophobic Spray Sealant +
After washing, spray on to wet *cold* panel, *one panel at a time*, leave on for a few *seconds*, hose off +
Less is more! +
Can be used for glass, paint, wheels, etc +
The hydrophobic surface helps dry a car at an accelerated rate whether it's with a sheet of water or a drying towel. See link:https://www.youtube.com/watch?v=fzc2VV5Zxyg[youTube]

1. *Chromance* - Hybrid Spray Wax +
start with a clean, dry vehicle, shake the bottle well, spray lightly onto a panel or microfibre towel, spread evenly, and buff with a dry microfiber cloth. +
Not for use on glass. Another link:https://www.youtube.com/watch?v=c77dB0p33wc&list=TLPQMjYwNTIwMjUuIo1Zn89XKw&index=2[youtube] video. +

=== TL;DR
1. Pre wash
1. snow foam
1. wheels
1. shampoo
1. tar remover
1. fallout remover
1. glass
1. interior
1. panel wipe
1. ceramic wax

++++
++++

* Citrus pre-wash:+
EzCC 5:1, Sam 5:1
* Arctic meltdown snow flame.
* Supernova shampoo
* Insta Gloss after wash, through snow cannon￼
* Geo Gel on the wheels
* Aurora on the lower part of the bodywork and rear bumper
* Fusion all over except the windscreen
* Lotus on outside glass
* Clarity 2.0 on the inside glass
* Wheel Armour to help the wheels stay fresh 
* Revolution on the tyres
* Sleek on interior plastics

=== Currently...
1. **Wheels**: EzCC: 10:1 +
50 ml : 500ml trigger pack
1. **Pre-wash**: 
a. EzCC-__Citrus__: 10:1 to 5:1 +
50ml : 500ml trigger pack
1. **Snow foam**:
a. Sam's : 20:1 +
50 ml : 1l
b. EzCC-__ArticMeltdown__ : 4:1 +
250ml : 1l

1. **Shampoo**:
a. EzCC-__Champs__: 1:250 +
40ml for 10l bucket


[%hardbreaks]
