:toc: left
:toclevels: 3
:toc-title: Contents
:sectnums:

:imagesdir: ./images

= Linux

== Install Brave on Ubunu etc

https://brave.com/linux/

Debian, Ubuntu, Mint:

 sudo apt install curl

 sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

 echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

 sudo apt update

 sudo apt install brave-browser



== Upgrade Ubuntu to latest Version
The basic workflow of a successful release upgrade is this:

1. Backup your data.
1. Return your system to as close to stock install as possible. Disable all non-Ubuntu sources, and uninstall all the packages that came from those sources.
1. Run a final sudo apt update and sudo apt upgrade. Fix ALL errors. Release-upgrades rarely fix package errors, but often make those errors worse.
1. [Optional] Prepare a LiveUSB installer. The "Try Ubuntu" environment is invaluable for fixing upgrade problems.
1. Run the release-upgrade. do-release-upgrade. Make sure you are on mains power (not battery), and on a reliable and fast network connection. Allow plenty of time (1-2 hours). Check the screen every few minutes -- the upgrader might pause awaiting your answer to a question.
1. Reboot into the newly-upgraded release of Ubuntu. Test your functions: Stream a movie to test your network, video, and audio. Test printing, webcam, microphone.
1. Review all of your add-on sources and applications. Some might be in the Ubuntu repositories now (no new source needed). Some might be no longer needed at all. Some sources might be incompatible with the new release of Ubuntu. Reinstall your add-on applications from trusted, compatible sources. Keep notes on what you added, and from where -- it really helps Step #2 next time.
1. Your data should be untouched by the upgrade. Check that your data is compatible with the new versions of your applications.

The most common problem encountered during a release-upgrade is NOT lost/corrupted data. The most common problem encountered is a package version conflict. Steps #2 and #7 might seem like a lot of work, but that's how you prevent the most common problem. DON'T skip these steps or take shortcuts.

If something goes very badly wrong, Steps #1 and #4 ensure that you can rebuild a working system from bare metal with all your data intact. Being prepared for problems is the best way to ensure that you don't encounter those problems.

== bash

=== Alias

[source,bash]
----
$ alias update="sudo apt-get update && sudo apt-get upgrade -y"
----

if needed permanently, put in `~/.bash_aliases` +
then can `source ~/.bash_aliases`

NOTE: aliases can also be in `~/.bashrc`

=== bashrc

[source,bash]
----
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias reboot="echo I\'m afraid I can\'t do that Dave"
alias cpbin2lpx='scp /home/ianc/shared/downloads/70PJ/70pj-upgrade-7.0.0-dev.bin root@lpx-000011:/home/transfer/upgrade/'
alias findinfiles='grep -irnI  --exclude=*.orig --exclude="moc_*.cpp" --exclude="Makefile*.*" --exclude=*.map --exclude=*.json --exclude=*.preset --exclude=*.autosave --exclude="preimage" --exclude="postimage" --exclude-dir="build_ccache"'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH="/.local/bin:$PATH"

function set-title() {
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$@\a\]"
  PS1=${ORIG}${TITLE}
}
----